# Generated by Django 3.2.13 on 2025-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_name', models.TextField(verbose_name='Название выигрыша')),
                ('win_percentage', models.FloatField(verbose_name='Поцент выигрыша')),
                ('dis_percentage', models.FloatField(verbose_name='Отображаемый процент')),
            ],
            options={
                'verbose_name': 'Розыгрыш',
                'verbose_name_plural': 'Розыгрыш',
                'db_table': 'draw',
            },
        ),
    ]
