# Generated by Django 4.2.11 on 2025-08-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draw',
            options={'verbose_name': 'Приз', 'verbose_name_plural': 'Призы'},
        ),
        migrations.AddField(
            model_name='draw',
            name='gifts_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draw',
            name='max_amount',
            field=models.FloatField(default=999999.0),
        ),
        migrations.AddField(
            model_name='draw',
            name='min_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='draw',
            name='dis_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='draw',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='win_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='draw',
            name='winning_name',
            field=models.CharField(max_length=255),
        ),
    ]
