# Generated by Django 4.2.11 on 2025-08-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_view', '0002_alter_draw_options_draw_gifts_link_draw_max_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(blank=True, verbose_name='Текст промпта')),
            ],
            options={
                'verbose_name': 'Глобальный промпт',
                'verbose_name_plural': 'Глобальные промпты',
            },
        ),
    ]
