# Generated by Django 4.2.11 on 2025-08-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw_view', '0003_globalprompt'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='globalprompt',
            table='GlobalPrompt',
        ),
    ]
