# Generated by Django 4.2.11 on 2025-08-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_view', '0004_alter_globalprompt_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalprompt',
            options={'verbose_name': 'Глобальный промпт', 'verbose_name_plural': 'Глобальный промпт'},
        ),
        migrations.AlterField(
            model_name='globalprompt',
            name='prompt_text',
            field=models.TextField(verbose_name='Текст промпта'),
        ),
        migrations.AlterModelTable(
            name='globalprompt',
            table=None,
        ),
    ]
