# Generated by Django 3.2.13 on 2025-07-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='номер кошелька')),
                ('winning_name', models.TextField(verbose_name='Название выигрыша')),
                ('id_trans', models.FloatField(blank=True, null=True, verbose_name='id трансакция')),
                ('date_register', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Розыгрыш',
                'verbose_name_plural': 'Розыгрыш',
                'db_table': 'log',
            },
        ),
    ]
