# Generated by Django 3.2.13 on 2025-08-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='id_trans',
            field=models.TextField(blank=True, null=True, verbose_name='id трансакция'),
        ),
    ]
