# Generated by Django 4.2.11 on 2025-08-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_view', '0002_alter_log_id_trans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Логи', 'verbose_name_plural': 'Логи'},
        ),
    ]
