# Generated by Django 4.2.11 on 2025-08-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_view', '0003_alter_log_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='amount',
            field=models.TextField(default='0-0', verbose_name='Диапазон'),
        ),
    ]
